### ISSUE TITLE
Generatin blazor(razor pagen in project)

### ISSUE THREAD

**Issue by timeshift92** [GobieGenerator/Gobie#18]
hello can i generate razor pages in my project using your generator?

**Comment by Siphonophora** [comment]
Hi @timeshift92 

Do you mean, generate the .razor files themselves?

**Comment by timeshift92** [comment]
yes generating razor file from model

**Comment by Siphonophora** [comment]
No. C# source generators can only generate C# directly. You might look at https://andrewlock.net/using-source-generators-to-generate-a-nav-component-in-a-blazor-app/ for an example of generating code used by a razor file. 

That said, this library isn't ready for any production use.

**Comment by timeshift92** [comment]
thanks found a way to generate

**Comment by timeshift92** [comment]
thanks found a way to generate
